- name: Add CentOS-Updates repository
  yum_repository:
    name: updates
    description: CentOS-Updates
    baseurl: http://mirror.centos.org/centos/7/updates/$basearch/

- name: Add CentOS-Extras repository
  yum_repository:
    name: extras
    description: CentOS-Extras
    baseurl: http://mirror.centos.org/centos/7/extras/$basearch/
